import { Artista, Obra, ContactoPlataforma } from '@/types/database';

export const MOCK_CONTACTOS_PLATAFORMA: ContactoPlataforma[] = [
  {
    id: 'plat-1',
    nombre_encargado: 'Dirección General (SuperAdmin)',
    whatsapp_email: '+53 5200 1122 | contacto@galeriacubana.art',
    activo: true,
    rol: 'superadmin',
    porcentaje_comision: 15,
    fecha_creacion: '2026-07-24T10:00:00Z',
  },
  {
    id: 'plat-2',
    nombre_encargado: 'Curador Principal de Arte',
    whatsapp_email: 'curaduria@galeriacubana.art',
    activo: true,
    rol: 'curador',
    porcentaje_comision: 5,
    foto_perfil: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200',
    fecha_creacion: '2026-07-25T10:00:00Z',
  },
  {
    id: 'plat-3',
    nombre_encargado: 'Atención al Coleccionista',
    whatsapp_email: 'ventas@galeriacubana.art',
    activo: true,
    rol: 'gestor',
    porcentaje_comision: 0,
    fecha_creacion: '2026-07-24T10:00:00Z',
  },
];

export const MOCK_ARTISTAS: Artista[] = [
  {
    id: 'art-1',
    nombre: 'Zaida del Río',
    bio: `Zaida del Río es una de las creadoras más representativas de las artes plásticas contemporáneas en Cuba. Nacida en Villa Clara en 1954, su producción abarca la pintura, el dibujo, el grabado, la cerámica y la ilustración de poesía.

Su lenguaje visual indaga en la espiritualidad, el budismo, el folclore afrocubano, la figura femenina en permanente metamorfosis con la fauna silvestre y la mitología tropical. Ha expuesto su obra en bienales de San Juan, Sao Paulo y Venecia, recibiendo reconocimientos internacionales de primer nivel.`,
    notas_taller: `“En la intimidad de mi taller en La Habana Vieja, trabajo escuchando el sonido de la brisa marina. Cada trazo en esta serie nace de una meditación profunda sobre la libertad y la metamorfosis de la mujer pájaro. No busco pintar la naturaleza como objeto exterior, sino como un estado de la conciencia.”`,
    provincia_ciudad: 'La Habana / Villa Clara',
    foto_perfil: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=500&auto=format&fit=crop',
    whatsapp_email_contacto: '+53 5288 9900 | zaida@artecubanostudio.com',
    contacto_directo: true,
    video_presentacion: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    fotos_galeria: [
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000',
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=1000',
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1000',
    ],
    documentos_pdf: [
      { titulo: 'Dossier Artístico Oficial 2026 (PDF)', url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' },
      { titulo: 'Currículum Vitae & Exposiciones (PDF)', url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' },
    ],
    contrato_firmado: true,
    comision_porcentaje: 20,
    fecha_registro: '2026-07-20T12:00:00Z',
  },
  {
    id: 'art-2',
    nombre: 'Tomás Sánchez',
    bio: `Tomás Sánchez (Aguada de Pasajeros, 1948) es un maestro indiscutible de la pintura de paisaje caribeño e hiperrealista. Estudió en la Escuela Nacional de Arte (ENA) y en el Instituto Superior de Arte (ISA) de La Habana.

Su obra explora la vasta inmensidad del paisaje tropical como santuario de meditación, alcanzando récords en casas de subastas internacionales como Christie's y Sotheby's.`,
    notas_taller: `“Para lograr el silencio en el cuadro, necesito pasar semanas construyendo capa por capa cada hoja y transparencia del agua. El paisaje es una invitación al recogimiento interior en medio del caos del mundo contemporáneo.”`,
    provincia_ciudad: 'Cienfuegos / La Habana',
    foto_perfil: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=500&auto=format&fit=crop',
    whatsapp_email_contacto: '+53 5299 4433 | tsanchez@estudioarte.cu',
    contacto_directo: true,
    video_presentacion: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    fotos_galeria: [
      'https://images.unsplash.com/photo-1582561624796-7a71f008cb4d?q=80&w=1000',
      'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1000',
    ],
    documentos_pdf: [
      { titulo: 'Catálogo Exposición Antológica (PDF)', url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' },
    ],
    contrato_firmado: true,
    fecha_registro: '2026-07-21T14:00:00Z',
  },
  {
    id: 'art-3',
    nombre: 'Wifredo Lam',
    bio: `Wifredo Lam (1902 - 1982) representa la cumbre universal de la pintura cubana moderna. Combinando elementos del surrealismo, el cubismo y la cosmovisión afrocubana, creó una síntesis plástica única en el arte del siglo XX.`,
    notas_taller: `“Quería pintar el drama de mi país, pero expresando plenamente el espíritu negro, la belleza del arte plástico de los negros. De esa manera, podía actuar como un caballo de Troya.”`,
    provincia_ciudad: 'Sagua la Grande, Villa Clara',
    foto_perfil: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=500&auto=format&fit=crop',
    whatsapp_email_contacto: 'contacto@galeriacubana.art',
    contacto_directo: false,
    video_presentacion: null,
    fotos_galeria: [
      'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?q=80&w=1000',
    ],
    documentos_pdf: [
      { titulo: 'Biografía Institucional & Archivo Histórico (PDF)', url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' },
    ],
    contrato_firmado: true,
    fecha_registro: '2026-07-22T09:00:00Z',
  },
  {
    id: 'art-4',
    nombre: 'Amelia Peláez',
    bio: `Amelia Peláez del Casal (1896 - 1968) fue una vanguardista cubana. Su obra trasladó los vitrales coloniales habaneros, las rejas de hierro forjado y las frutas tropicales a una estructura plástica moderna.`,
    notas_taller: `“El color y la luz de La Habana no se pueden imitar con fórmulas europeas; se capturan a través del ritmo de la arquitectura barroca colonial y la calidez del hogar cubano.”`,
    provincia_ciudad: 'La Habana',
    foto_perfil: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=500&auto=format&fit=crop',
    whatsapp_email_contacto: 'info@galeriacubana.art',
    contacto_directo: false,
    video_presentacion: null,
    fotos_galeria: [],
    documentos_pdf: [],
    contrato_firmado: true,
    fecha_registro: '2026-07-23T11:00:00Z',
  },
];

export const MOCK_OBRAS: Obra[] = [
  {
    id: 'obra-1',
    artista_id: 'art-1',
    titulo: 'Danza Nocturna y la Luna de Agua',
    descripcion: 'Pintura expresiva de gran formato en tonos azur y dorado. Obra emblemática de la serie de metamorfosis figurativa.',
    analisis_curatorial: 'Esta obra representa un punto de inflexión en la etapa madura de Zaida del Río. La delicada integración de tintas gestuales con acrílico de alta pigmentación genera una atmósfera hipnótica. Destaca el dominio del claroscuro y la fuerza simbólica del ojo lunar como testigo del rito sagrado.',
    opciones_envio: '✈️ Envío internacional seguro: Lienzo profesional desmontado y enrollado en tubo rígido de alta resistencia con certificado de exportación y seguro de tránsito incluido.',
    historial_exposiciones: [
      'Exposición Colectiva de Arte Cubano Contemporáneo (La Habana, 2024)',
      'Muestra Especial de Pintura Caribeña (Madrid, 2025)',
      'Registro en el Catálogo de la Galería Virtual de Arte Cubano (2026)',
    ],
    tecnica: 'Acrílico y tinta sobre lienzo',
    medidas: '140 x 180 cm',
    año: 2024,
    precio_referencia: 4500,
    comision_porcentaje: 20,
    es_exclusiva: true,
    disponible: true,
    imagenes: [
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1200&auto=format&fit=crop',
    ],
    fecha_creacion: '2026-07-24T11:00:00Z',
    artista: MOCK_ARTISTAS[0],
  },
  {
    id: 'obra-2',
    artista_id: 'art-2',
    titulo: 'Meditación en la Laguna Azul',
    descripcion: 'Paisaje monumental que transmite silencio, escala épica y serenidad espiritual en la naturaleza exuberante.',
    analisis_curatorial: 'Tomás Sánchez logra una escala lírica donde la naturaleza deja de ser mera representación botánica para convertirse en un santuario espiritual. La textura del follaje y el espejo de agua transmiten una serenidad meditativa inigualable.',
    opciones_envio: '✈️ Envío internacional seguro: Lienzo enrollado en tubo de grado museo con certificado de exportación oficial y seguro contra todo riesgo durante el transporte.',
    historial_exposiciones: [
      'Retrospectiva del Paisaje Cubano (Cienfuegos, 2023)',
      'Fiera de Arte Contemporáneo (Miami, 2024)',
      'Galería Virtual de Arte Cubano (2026)',
    ],
    tecnica: 'Óleo sobre lienzo',
    medidas: '160 x 220 cm',
    año: 2023,
    precio_referencia: 8500,
    comision_porcentaje: 20,
    es_exclusiva: true,
    disponible: true,
    imagenes: [
      'https://images.unsplash.com/photo-1582561624796-7a71f008cb4d?q=80&w=1200&auto=format&fit=crop',
    ],
    fecha_creacion: '2026-07-24T11:05:00Z',
    artista: MOCK_ARTISTAS[1],
  },
  {
    id: 'obra-3',
    artista_id: 'art-3',
    titulo: 'Ritmos Tropicales V',
    descripcion: 'Composición icónica donde conviven formas totémicas, vegetación autóctona y misticismo figurativo.',
    analisis_curatorial: 'Pieza maestra de síntesis vanguardista. Lam combina trazos incisivos que evocan la deidad afrocubana con la estructura formal del cubismo europeo.',
    opciones_envio: '✈️ Envío internacional seguro: Embalaje rígido especializado para obras de colección patrimonial con documentación aduanal y certificado de autenticidad.',
    historial_exposiciones: [
      'Colección Privada Familiar (París - La Habana)',
      'Exposición Histórica de la Vanguardia Cubana (2022)',
    ],
    tecnica: 'Óleo y carboncillo sobre tela',
    medidas: '120 x 100 cm',
    año: 2022,
    precio_referencia: 12000,
    comision_porcentaje: 20,
    es_exclusiva: true,
    disponible: true,
    imagenes: [
      'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?q=80&w=1200&auto=format&fit=crop',
    ],
    fecha_creacion: '2026-07-24T11:10:00Z',
    artista: MOCK_ARTISTAS[2],
  },
  {
    id: 'obra-4',
    artista_id: 'art-4',
    titulo: 'Vitral Colonial y Frutas',
    descripcion: 'Juego de geometrías, líneas gruesas en negro y matices vivos inspirados en los vitreaux habaneros.',
    analisis_curatorial: 'En este lienzo, Amelia Peláez eleva la ornamentación doméstica habanera a la categoría de estructura plástico-arquitectónica monumental.',
    opciones_envio: '✈️ Envío internacional seguro: Tubo protector térmico de alta seguridad con guía de seguimiento internacional y certificado oficial.',
    historial_exposiciones: [
      'Salón Nacional de Artes Plásticas (La Habana)',
      'Galería Virtual de Arte Cubano (2026)',
    ],
    tecnica: 'Óleo sobre lienzo',
    medidas: '110 x 90 cm',
    año: 2024,
    precio_referencia: 3800,
    comision_porcentaje: 20,
    es_exclusiva: true,
    disponible: true,
    imagenes: [
      'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?q=80&w=1200&auto=format&fit=crop',
    ],
    fecha_creacion: '2026-07-24T11:15:00Z',
    artista: MOCK_ARTISTAS[3],
  },
];
